### ISSUE TITLE
Batch size affects metrics (chi2, rmsd)

### ISSUE THREAD

**Issue by ktamiola** [PeptoneInc/dspp-keras#15]
Insofar we are reporting collective CHI2 per whole batch. Consequently, the CHI2 values are pathologically big. We should be able to pass batch size as a parameter of get it from Keras.Callback class and divide the CHI2 by it.

**Comment by jandom** [comment]
Does this apply also to RMSD, ie is RMSD also requiring a batch average?

**Comment by ktamiola** [comment]
Indeed @jandom. Both RMSD and CHI2 are affected by batch sizes.
