### ISSUE TITLE
Restart functionality

### ISSUE THREAD

**Issue by ktamiola** [PeptoneInc/dspp-keras#20]
We simply need to have an ability to restart training. I could envision that as an extension of `dspp_utils.py`. We could use built-in Keras `Checkpoint` callbacks.

**Comment by jandom** [comment]
It's all about the scope of what we want to do here – i'm guessing there are plenty of keras examples on restarts out there, we should focus features on what we have an 'competitive advantage' – sth specific to NMR/protein data, not handling keras IO

Proposing to close

**Comment by ktamiola** [comment]
@jandom agreed!
