### ISSUE TITLE
Error to Download data with Python3

### ISSUE THREAD

**Issue by ghost** [PeptoneInc/dspp-keras#23]
Hi.
when downloading the datasets, the `dspp.py` module raises the following error in python3.
`TypeError: the JSON object must be str, not 'bytes'`

The main reason explains [here](https://stackoverflow.com/questions/34619898/python3-typeerror-the-json-object-must-be-str-not-bytes).

The fast solution is provided [here](https://stackoverflow.com/questions/6862770/python-3-let-json-object-accept-bytes-or-let-urlopen-output-strings) as the first answer, which works for both Py2 and Py3.

**Comment by ktamiola** [comment]
Thank you for reporting, we are looking into it right now.

**Comment by ktamiola** [comment]
Dear @ErmiaAzarkhalili the issue should be fixed. Please re-open if any #23 related behaviour is still observed. Thank you for using `dspp-keras`

**Comment by jandom** [comment]
@ktamiola this should be resolved now: pushed out 0.0.5 to pip as well as github

@ErmiaAzarkhalili big props for reporting the problem (together with a solution!). can you please let us know if it's working for you now?

**Comment by ghost** [comment]
@ktamiola thank you for quick update.
@jandom I will give it a try tomorrow morning.
Your package is great, I will be utilizing it, and keep you posted about about possible issues.
